### PR TITLE
Fix loop sync

### LINKED ISSUE #9: Make `unistd` as part of if else
Hi there!
It's looks so nice <3

Just add `<unistd.h>` to if else statement, and maybe some `readme`'s for linux too ?
```c++
#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif 
```

### LINKED ISSUE #12: Sleep is a Windows function
I was trying to compile this amazing work, but on Unix there is slight difference in sleep function.
`Sleep` is a Windows function
For Unix, `nanosleep` or `usleep`
https://stackoverflow.com/questions/10976176/c-error-sleep-was-not-declared-in-this-scope

This is the line, where I ran into problem with compiling on Mint and g++ 9.3.0.
https://github.com/DinoZ1729/Ray/blob/b6a9dbd6c74162ca9fea685ec0e7e7fcb5a7cf3c/main.cpp#L207

So, I replaced Sleep with usleep and uncomment `#include <unistd.h>` line and it solved my problem.

I'm not a cpp guy, but I think this issue is on point. What do you think?

### PR DESCRIPTION
**Pull request by hlouzada**
Substitute the sleep time inside the loop with the remaining time to finish the frame in 17ms for about 59fps (Ty @millennIumAMbiguity). Using thread to sleep for a better precision and independence of OS.
fixes #12
fixes #9 as it's not necessary

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -138,6 +140,9 @@ class camera {
   }
 };
 
+//using a fixed timestep of 1/60(fps) for each frame
+constexpr std::chrono::nanoseconds timestep(16ms);
```
Comment (millennIumAMbiguity) [inline main.cpp:144]: 16ms is a little above 62 fps, 17ms is about 59 fps. 
This is why it's common to see 59hz displays. I would recommend using the standard 17ms.
```suggestion
constexpr std::chrono::nanoseconds timestep(17ms);	
```

**Comment by Shroomerian** [comment]
Fine work! Wouldn't have figured it out myself. Hope this gets merged.

**Comment by hlouzada** [comment]
@DinoZ1729 just fixed the conflicts with 😄
